// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHO7JhAeJp8Hz4IiWCvNNFpRxI9n59jsc',
    appId: '1:695524442153:android:9fccfbcec28e6e70e25c38',
    messagingSenderId: '695524442153',
    projectId: 'kopichat-d6a07',
    storageBucket: 'kopichat-d6a07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL_OwQgDiql5xCyz3XmJzUHWaXOkq-7KM',
    appId: '1:695524442153:ios:b4415576e086063de25c38',
    messagingSenderId: '695524442153',
    projectId: 'kopichat-d6a07',
    storageBucket: 'kopichat-d6a07.appspot.com',
    androidClientId: '695524442153-l3kid9l2ib63opgkr1h17b7776e5oa57.apps.googleusercontent.com',
    iosClientId: '695524442153-euf8l7akcjmpp42lkeb5a1jbn73djsse.apps.googleusercontent.com',
    iosBundleId: 'com.example.kopichat',
  );
}
